### ISSUE TITLE
Can I use StegoTorus without Tor

### ISSUE THREAD

**Issue by testcaoy7** [SRI-CSL/stegotorus#3]
It appears that the StegoTorus has built-in SOCKS5 proxy module.
Can I use StegoTorus without Tor and as a proxy server ?
Like this:

Browser (using SOCKS5 proxy) -->  StegoTorus Client (Listen at 127.0.0.1:1080) --> StegoTorus Server (Listen at server_ip:80) --> World Wide Web

**Comment by ianamason** [comment]
Gosh it has been a while. Is it socks5? I seem to remember socks4a. But irregardless we do not rely on anything too torish, so you may be able to hook it up like this.

**Comment by testcaoy7** [comment]
I may even able to hook StegoTorus with other tools as well (such as Shadowsocks). Thank you for the reply.
